//! Credential hashing for the auth adapters.
//!
//! Two different jobs, two different primitives:
//!
//! - **Passwords** are low-entropy and chosen by a human, so they need a slow
//!   KDF. Argon2id with the crate defaults (the OWASP baseline: 19 MiB, t=2,
//!   p=1) and a random per-password salt.
//! - **API keys** are 128-bit random UUIDs generated by us. There is nothing to
//!   brute-force, so a single SHA-256 pass is enough — and it keeps key lookup
//!   cheap enough to do on every request.

use argon2::password_hash::{
    rand_core::OsRng, PasswordHash, PasswordHasher, PasswordVerifier, SaltString,
};
use argon2::Argon2;
use sha2::{Digest, Sha256};
use std::fmt::Write;

/// Hash a login password for storage.
///
/// Panics only if Argon2 rejects its own default parameters, which cannot
/// happen at runtime.
pub fn hash_password(password: &str) -> String {
    let salt = SaltString::generate(&mut OsRng);
    Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .expect("argon2 hashing with default parameters")
        .to_string()
}

/// Verify a login attempt against a stored hash. A missing password, or a
/// stored value that is not a PHC string, is a failed login — never a match.
pub fn verify_password(stored_hash: &str, provided: Option<&str>) -> bool {
    let Some(provided) = provided else {
        return false;
    };
    let Ok(parsed) = PasswordHash::new(stored_hash) else {
        return false;
    };
    Argon2::default()
        .verify_password(provided.as_bytes(), &parsed)
        .is_ok()
}

/// True if the value is something [`verify_password`] could match against.
/// Used to spot pre-hashing files on load and upgrade them in place.
pub fn is_password_hash(value: &str) -> bool {
    PasswordHash::new(value).is_ok()
}

/// Hash an API key for storage. Deterministic, so lookup is a hash of the
/// bearer token compared against stored hashes.
pub fn hash_api_key(key: &str) -> String {
    Sha256::digest(key.as_bytes())
        .iter()
        .fold(String::with_capacity(64), |mut out, byte| {
            let _ = write!(out, "{byte:02x}");
            out
        })
}

/// True if the value is already a [`hash_api_key`] digest rather than a raw
/// key. Used to spot pre-hashing files on load and upgrade them in place.
pub fn is_api_key_hash(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn password_round_trips() {
        let hash = hash_password("hunter2");
        assert!(hash.starts_with("$argon2"));
        assert!(!hash.contains("hunter2"));
        assert!(verify_password(&hash, Some("hunter2")));
        assert!(!verify_password(&hash, Some("hunter3")));
        assert!(!verify_password(&hash, None));
    }

    #[test]
    fn same_password_hashes_differently() {
        assert_ne!(hash_password("hunter2"), hash_password("hunter2"));
    }

    #[test]
    fn plaintext_is_not_a_password_hash() {
        assert!(!is_password_hash("password"));
        assert!(!verify_password("password", Some("password")));
        assert!(is_password_hash(&hash_password("password")));
    }

    #[test]
    fn api_key_hash_is_stable_and_not_the_key() {
        let key = "0d9e6d2c-1f0b-4b0a-9c2a-2d1f0b4b0a9c";
        let hash = hash_api_key(key);
        assert_eq!(hash, hash_api_key(key));
        assert_ne!(hash, key);
        assert!(is_api_key_hash(&hash));
        assert!(!is_api_key_hash(key));
    }
}
