description: "A project defining a schema namespace"
pathTemplate: "${project}/project"
properties:
  project:
    type: slug
    segments: 2
    createOnly: true
  label:
    type: string
  description:
    type: string
