version: 1
scope: global
description: "A site configuration that maps to a namespace and dataset"
filePathTemplate: "projects/${namespace}/sites/${site_id}"
properties:
  site_id:
    type: string
  project:
    type: string
  name:
    type: string
  namespace:
    type: string
  version:
    type: string
  dataset:
    type: string
