description: "A site configuration that maps to a namespace and dataset"
filePathTemplate: "${project}/sites/${name}.yaml"
properties:
  project:
    type: slug
    segments: 2
    createOnly: true
  name:
    type: slug
    createOnly: true
  label:
    type: string
  version:
    type: string
  dataset:
    type: string
