version: 1
description: "A site configuration that maps to a namespace and dataset"
filePathTemplate: "${namespace}/sites/${site_id}.yaml"
properties:
  site_id:
    type: string
  project:
    type: string
  name:
    type: string
  namespace:
    type: string
  version:
    type: string
  dataset:
    type: string
